name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag zhenshaw/cadvisor:0.37.5
      
    - name: Login to Docker
      run: echo "$docker_password" | docker login -u "$docker_username" --password-stdin
      
    - name: Push docker image
      run: docker push zhenshaw/cadvisor:0.37.5
