name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/zhenshaw/docker-proxy:cadvisor  && docker push ghcr.io/zhenshaw/docker-proxy:cadvisor
